apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-frontend-svc
spec:
  type: ClusterIP
  selector:
    app: company-portal-frontend-label
  ports:
    - port: 80
      targetPort: 8081