apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# Reference to shared base
resources:
  - ../../base

# Optional: Apply name prefix/suffix
nameSuffix: -prod
namespace: company-portal-ns-prod
replicas:
  - name: company-portal-frontend-deployment
    count: 3
images:
  - name: docker.io/sureshtamizan/company_portal_frontend
    newTag: 2.0.0