apiVersion: v2
name: app1-chart
description: A Helm chart to deploy nginx using NodePort service
type: application
version: 0.1.1
appVersion: "2.0"
home: https://www.youtube.com/@tech-picnic
maintainers:
  - name: Suresh R
    email: tech-picnic@gmail.com
keywords:
  - nginx
  - demo
  - kubernetes
  - helm