apiVersion: v1
kind: Service
metadata:
  name: company-portal-frontend-svc
spec:
  selector:
    app: company-portal-frontend-label
  type: ClusterIP
  ports:
    - port: 80  # Service Port that is exposed on the Service itself. Usage: If another pod wants to reach your shopping cart, it will call http://shopping-cart-svc:80.
      targetPort: 8081 # Container port from Pod
